### ISSUE TITLE
Proposal: Creating a deployment/replicaset

### ISSUE THREAD

**Issue by penumbra23** [postfinance/hlfabric-k8scc#21]
Hi! 👋 

First of, thanks for the awesome external builder!

It's not an issue exactly, but more like some enhancement proposal. Since now the builder is creating a single pod, would it make sense to make it a deployment or at least a replica set? In that way the chaincode has at least some restart policies in case of node failing.

**Comment by djboris9** [comment]
Hi @mirioeggmann 

Can you have a look at it? I'm no more at PostFinance

**Comment by penumbra23** [comment]
Actually, I've tested this one out. Each time an endorsement is requested, the peer checks if the CC pod is running. If it's not there, it starts a new instance. This also works when the peer restarts, the old CC pod crashes because it can't sync with the restarted peer and the newly created peer creates a new running pod. So it should be fine also to have the CC pod running as a plain K8s Pod.

Nice job! I'll close the issue
