### ISSUE TITLE
A tutorial to help newbies use the utility would help!

### ISSUE THREAD

**Issue by sillysachin** [postfinance/hlfabric-k8scc#3]

**Comment by djboris9** [comment]
Indeed, we only have a minimalistic [Usage](https://github.com/postfinance/hlfabric-k8scc#usage) section in the readme. Is there something specific you had issues with? In order to cover it in a tutorial

**Comment by sillysachin** [comment]
For a beginner with familiarity with fabric samples. How does one start with using this repo. I am guessing the repo assumes a host of skills required to be known to start. At least a pre-requisites would help .

**Comment by mirioeggmann** [comment]
Hi @sillysachin 
I added a initial [demo](https://github.com/postfinance/hlfabric-k8scc/tree/master/example/demo) in the example folder of the repository. Can you give me a feedback if that corresponds to your ideas and helps you to get started with the utility?

**Comment by sillysachin** [comment]
Yes. Will try this out this week and update if i could follow it successfully  :). 

Thanks for the response.
