### ISSUE TITLE
/healthz endpoint fails

### ISSUE THREAD

**Issue by aldredb** [postfinance/hlfabric-k8scc#4]
After the peer starts, the `/healthz` endpoint fails with the following error:

```
{"status":"Service Unavailable","time":"2020-06-24T09:51:14.845961762Z","failed_checks":[{"component":"docker","reason":"failed to ping to Docker daemon: Get \"http://unix.sock/_ping\": dial unix /var/run/docker.sock: connect: no such file or directory"}]}%
```

The solution is to delete the `vm` section in `core.yaml`

**Comment by djboris9** [comment]
Hi @aldredb 

May I ask you, how does your environment/deployment look like? Especially the peer version and the `externalBuilders` section of `core.yaml`. Did you use the prebuild Docker images or did you build your own ones?

So far I wasn't able to reproduce this issue.

I guess the issue could be one of these:
- `core.yaml` couldn't be patched or was incorrectly patched with the `externalBuilders`
- the external builder binaries can't be found and the external builder is disabled, so it's falling back to docker

Could you also provide more logs of the peer? Maybe switch it to `DEBUG` level and grep it for `k8s` and `external`.

**Comment by aldredb** [comment]
@djboris9 I modified the example to illustrate the issue: https://github.com/aldredb/hlfabric-k8scc/blob/master/example/demo/k8s/components/peer0.org1.example.com.yaml

You'll see that I activated the operations endpoint and `readinessCheck`. When you run the demo, you'll see that the peers will never be in READY state because of the error in `/healthz` endpoint

```
NAME                                          READY   STATUS      RESTARTS   AGE
cli.peer0.org1.example.com-7db644b56c-s99xc   1/1     Running     0          3m23s
cli.peer0.org2.example.com-55bfb5c587-s6r2k   1/1     Running     0          3m23s
orderer.example.com-6b7d459cb7-bnvkb          1/1     Running     0          3m23s
peer0.org1.example.com-f65f45b4c-j8lt5        0/1     Running     0          3m22s
peer0.org2.example.com-b7c6b6d4f-wbr5x        0/1     Running     0          3m22s
setup-bmd97                                   0/1     Completed   0          3m25s
```

Anyways as I mentioned in my original post, the solution is to remove `vm` section in `core.yaml` as `externalBuilders` is already enabled.

**Comment by aldredb** [comment]
@djboris9 Anyways I fixed the issue. I created a PR for the demo for your consideration: https://github.com/postfinance/hlfabric-k8scc/pull/8

**Comment by djboris9** [comment]
Thanks @aldredb for your contribution!
